version: '3'
services:
  keyword:
    image: gwangjang/keyword
    depends_on:
      - eureka
      - apigateway
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
    ports:
      - 8081:8081
    networks:
      - msa-network
    build: ./KeywordService
    
  eureka:
    image: gwangjang/eureka:latest
    ports:
      - 8761:8761 # Eureka 서비스 포트 설정
    networks:
      - msa-network
      
networks:
  msa-network:
