version: '3'
services:
  apigateway:
    image: gwangjang/apigateway
    ports:
      - 8888:8888
    networks:
      - msa-network

  eureka:
    image: gwangjang/eureka:latest
    ports:
      - 8761:8761
    networks:
      - msa-network
  keyword:
    image: gwangjang/keyword
    depends_on:
      - eureka
      - apigateway
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
    ports:
      - 8081:8081
    networks:
      - msa-network
    build: ./KeywordService

networks:
  msa-network:
