  name: Java CI with Gradle
  
  on:
    push:
      branches: [ "master" ]
    pull_request:
      branches: [ "master" ]
  
  permissions:
    contents: read
  
  jobs:
    build:
  
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Make application.yml
        run: |
          mkdir -p src/main/resources
          echo "$APPLICATION" > src/main/resources/application.yml
        env:
          APPLICATION: ${{ secrets.APPLICATION }}
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
  
      - name: Build with Gradle
        run: ./gradlew build -x test
  
      - name: Docker build
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t app .
          docker tag app ${{ secrets.DOCKER_USERNAME }}/keyword:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/keyword:latest
            
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} 
          username: ec2-user
          key: ${{ secrets.PRIVATE_KEY }} 
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/keyword:latest
            docker image prune -a -f
            docker-compose up -d
     
